name: Build, push, and deploy app to dev and prod

on:
  workflow_dispatch: # TODO legg til ved push til main når vi er klare for å deploye til prod

env:
  IMAGE: ghcr.io/navikt/familie-ef-minside:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - name: Npm install and build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          npm ci
          npm run build
      - name: Npm build server
        working-directory: ./server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          npm ci
          npm run build
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          docker build . -t ${IMAGE}
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE}
  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yaml
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais-prod.yaml
